diff --git a/geth/Dockerfile b/geth/Dockerfile
index 7316271..86e9a33 100644
--- a/geth/Dockerfile
+++ b/geth/Dockerfile
@@ -9,7 +9,11 @@ RUN git clone $REPO --branch op-node/$VERSION --single-branch . && \
     git switch -c branch-$VERSION && \
     bash -c '[ "$(git rev-parse HEAD)" = "$COMMIT" ]'
 
-RUN cd op-node && \
+# Patch to handle the legacy ConfigUpdate event GAS_CONFIG_ECOTONE that shouldn't be used anymore
+# Emitted only on Lisk Sepolia from the SystemConfig contract
+COPY op-node-lisk-hotfix.patch .
+RUN git apply op-node-lisk-hotfix.patch && \
+    cd op-node && \
     make VERSION=$VERSION op-node
 
 FROM golang:1.22 AS geth
diff --git a/reth/Dockerfile b/reth/Dockerfile
index 0144140..bbb833f 100644
--- a/reth/Dockerfile
+++ b/reth/Dockerfile
@@ -9,7 +9,11 @@ RUN git clone $REPO --branch op-node/$VERSION --single-branch . && \
     git switch -c branch-$VERSION && \
     bash -c '[ "$(git rev-parse HEAD)" = "$COMMIT" ]'
 
-RUN cd op-node && \
+# Patch to handle the legacy ConfigUpdate event GAS_CONFIG_ECOTONE that shouldn't be used anymore
+# Emitted only on Lisk Sepolia from the SystemConfig contract
+COPY op-node-lisk-hotfix.patch .
+RUN git apply op-node-lisk-hotfix.patch && \
+    cd op-node && \
     make VERSION=$VERSION op-node
 
 FROM rust:1.82 AS reth
