#!/bin/bash
set -eu

echoBanner() {
	echo -e "\n------------------------------------------------------------------------------------------------------------"
	echo -e "$@"
	echo -e "------------------------------------------------------------------------------------------------------------\n"
}

VERBOSITY=${GETH_VERBOSITY:-3}
GETH_DATA_DIR=/data
RPC_PORT="${RPC_PORT:-8545}"
WS_PORT="${WS_PORT:-8546}"
AUTHRPC_PORT="${AUTHRPC_PORT:-8551}"
METRICS_PORT="${METRICS_PORT:-6060}"
HOST_IP="" # put your external IP address here and open port 30303 to improve peer connectivity
P2P_PORT="${P2P_PORT:-30303}"
ADDITIONAL_ARGS=""
OP_GETH_GCMODE="${OP_GETH_GCMODE:-full}"
OP_GETH_SYNCMODE="${OP_GETH_SYNCMODE:-full}"

# TODO: Enable this check once Lisk configs are added to the superchain registry repo
# if [[ -z "$OP_NODE_NETWORK" ]]; then
#     echo "expected OP_NODE_NETWORK to be set" 1>&2
#     exit 1
# fi

# Ensure data directory exists
mkdir -p $GETH_DATA_DIR

# Init genesis
echoBanner "Initializing data directory under '${GETH_DATA_DIR}'"
./geth init --datadir=$GETH_DATA_DIR "$GENESIS_FILE_PATH"

# Download and apply snapshot, when configured
(. download-apply-snapshot.sh)

# Set the start flags
echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"

if [ "${OP_GETH_ETH_STATS+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --ethstats=$OP_GETH_ETH_STATS"
fi

if [ "${OP_GETH_ALLOW_UNPROTECTED_TXS+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --rpc.allow-unprotected-txs=$OP_GETH_ALLOW_UNPROTECTED_TXS"
fi

if [ "${OP_GETH_STATE_SCHEME+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --state.scheme=$OP_GETH_STATE_SCHEME"
fi

if [ "${OP_GETH_BOOTNODES+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --bootnodes=$OP_GETH_BOOTNODES"
fi

if [ "${HOST_IP:+x}" = x ]; then
	ADDITIONAL_ARGS="$ADDITIONAL_ARGS --nat=extip:$HOST_IP"
fi

# Start service
echoBanner "Starting op-geth execution node..."
./geth \
    --datadir="$GETH_DATA_DIR" \
    --verbosity="$VERBOSITY" \
    --authrpc.addr=0.0.0.0 \
    --authrpc.port="$AUTHRPC_PORT" \
    --authrpc.vhosts="*" \
    --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
    --ws \
    --ws.addr=0.0.0.0 \
    --ws.port="$WS_PORT" \
    --ws.origins="*" \
    --ws.api=debug,eth,net,engine \
    --http \
    --http.corsdomain="*" \
    --http.vhosts="*" \
    --http.addr=0.0.0.0 \
    --http.port="$RPC_PORT" \
    --http.api=web3,debug,eth,net,engine \
    --metrics \
    --metrics.addr=0.0.0.0 \
    --metrics.port="$METRICS_PORT" \
    --syncmode="$OP_GETH_SYNCMODE" \
    --gcmode="$OP_GETH_GCMODE" \
    --port="$P2P_PORT" \
    --maxpeers=100 \
    --rollup.sequencerhttp="$SEQUENCER_HTTP" \
    --rollup.halt=major \
    --rollup.disabletxpoolgossip=true \
    $ADDITIONAL_ARGS # intentionally unquoted

# Add the following flag(s) after Lisk is added to the Superchain Registry
    # --op-network="$OP_NODE_NETWORK"
