#!/bin/bash
set -eu

echoBanner() {
	echo -e "\n------------------------------------------------------------------------------------------------------------"
	echo -e "$@"
	echo -e "------------------------------------------------------------------------------------------------------------\n"
}

RETH_DATA_DIR=/data
RPC_PORT="${RPC_PORT:-8545}"
WS_PORT="${WS_PORT:-8546}"
AUTHRPC_PORT="${AUTHRPC_PORT:-8551}"
METRICS_PORT="${METRICS_PORT:-6060}"
P2P_PORT="${P2P_PORT:-30303}"

# Ensure data directory exists
mkdir -p $RETH_DATA_DIR

# Set the start flags
echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"

# Start service
echoBanner "Starting op-reth execution node under '${RETH_DATA_DIR}'..."
exec ./op-reth node \
    -vvv \
    --chain="$GENESIS_FILE_PATH" \
    --datadir="$RETH_DATA_DIR" \
    --log.stdout.format log-fmt \
    --authrpc.addr=0.0.0.0 \
    --authrpc.port="$AUTHRPC_PORT" \
    --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
    --ws \
    --ws.origins="*" \
    --ws.addr=0.0.0.0 \
    --ws.port="$WS_PORT" \
    --ws.api=debug,eth,net,txpool \
    --http \
    --http.corsdomain="*" \
    --http.addr=0.0.0.0 \
    --http.port="$RPC_PORT" \
    --http.api=web3,debug,eth,net,txpool \
    --metrics=0.0.0.0:"$METRICS_PORT" \
    --disable-discovery \
    --port="$P2P_PORT" \
    --rollup.sequencer-http=$SEQUENCER_HTTP \
    --rollup.disable-tx-pool-gossip
