#!/bin/bash
set -eu

RETH_DATA_DIR=/data
RPC_PORT="${RPC_PORT:-8545}"
WS_PORT="${WS_PORT:-8546}"
AUTHRPC_PORT="${AUTHRPC_PORT:-8551}"
METRICS_PORT="${METRICS_PORT:-6060}"

if [[ -z "$RETH_CHAIN" ]]; then
    echo "expected RETH_CHAIN to be set" 1>&2
    exit 1
fi

if [ "${OP_NODE_OVERRIDE_CANYON+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --override.canyon=$OP_NODE_OVERRIDE_CANYON"
fi

mkdir -p $RETH_DATA_DIR
echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"

exec ./op-reth node \
  -vvv \
  --datadir="$RETH_DATA_DIR" \
  --log.stdout.format log-fmt \
  --ws \
  --ws.origins="*" \
  --ws.addr=0.0.0.0 \
  --ws.port="$WS_PORT" \
  --ws.api=debug,eth,net,txpool \
  --http \
  --http.corsdomain="*" \
  --http.addr=0.0.0.0 \
  --http.port="$RPC_PORT" \
  --http.api=debug,eth,net,txpool \
  --authrpc.addr=0.0.0.0 \
  --authrpc.port="$AUTHRPC_PORT" \
  --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
  --metrics=0.0.0.0:"$METRICS_PORT" \
  --chain="$GENESIS_FILE_PATH" \
  --disable-discovery \
  --rollup.sequencer-http=$SEQUENCER_HTTP \
  --rollup.disable-tx-pool-gossip \
  $ADDITIONAL_ARGS